// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dfToString
std::string dfToString(NumericMatrix coeff, List lsnames);
RcppExport SEXP polyAlgebra_dfToString(SEXP coeffSEXP, SEXP lsnamesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type coeff(coeffSEXP);
    Rcpp::traits::input_parameter< List >::type lsnames(lsnamesSEXP);
    __result = Rcpp::wrap(dfToString(coeff, lsnames));
    return __result;
END_RCPP
}
// fastMult
std::string fastMult(NumericMatrix coeff, List lsnames);
RcppExport SEXP polyAlgebra_fastMult(SEXP coeffSEXP, SEXP lsnamesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type coeff(coeffSEXP);
    Rcpp::traits::input_parameter< List >::type lsnames(lsnamesSEXP);
    __result = Rcpp::wrap(fastMult(coeff, lsnames));
    return __result;
END_RCPP
}
