// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fastMult
std::string fastMult(NumericMatrix coeff, List lsnames, bool flt, NumericVector erows);
RcppExport SEXP polyAlgebra_fastMult(SEXP coeffSEXP, SEXP lsnamesSEXP, SEXP fltSEXP, SEXP erowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type coeff(coeffSEXP);
    Rcpp::traits::input_parameter< List >::type lsnames(lsnamesSEXP);
    Rcpp::traits::input_parameter< bool >::type flt(fltSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type erows(erowsSEXP);
    __result = Rcpp::wrap(fastMult(coeff, lsnames, flt, erows));
    return __result;
END_RCPP
}
