# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

poly_aggregate <- function(a, dotM) {
    .Call('polyAlgebra_poly_aggregate', PACKAGE = 'polyAlgebra', a, dotM)
}

fastMult <- function(coeff, lsnames, flt, erows) {
    .Call('polyAlgebra_fastMult', PACKAGE = 'polyAlgebra', coeff, lsnames, flt, erows)
}

