# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dfToString <- function(coeff, lsnames) {
    .Call('polyAlgebra_dfToString', PACKAGE = 'polyAlgebra', coeff, lsnames)
}

fastMult <- function(coeff, lsnames) {
    .Call('polyAlgebra_fastMult', PACKAGE = 'polyAlgebra', coeff, lsnames)
}

