# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ugly_order <- function(x, f) {
    .Call('polyAlgebra_ugly_order', PACKAGE = 'polyAlgebra', x, f)
}

dfToString <- function(coeff_in, lsnames, flt, foo) {
    .Call('polyAlgebra_dfToString', PACKAGE = 'polyAlgebra', coeff_in, lsnames, flt, foo)
}

fastMult <- function(coeff, lsnames, flt, foo) {
    .Call('polyAlgebra_fastMult', PACKAGE = 'polyAlgebra', coeff, lsnames, flt, foo)
}

